# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mariadb
            - redis
            - mongodb
    mariadb:
        platform: linux/x86_64
        container_name: mariadb
        image: mariadb:10.5.8
        ports:
          - ${MYSQL_EXPOSE_PORT}:3306
        environment:
         MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        networks:
          - sail
        volumes:
          - ${MYSQL_DATA}:/var/lib/mysql
    redis:
        container_name: laravel-redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          retries: 3
          timeout: 5s
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        command: [--auth]
        ports:
        - ${MONGO_DB_PORT}:27017
        volumes:
        - ${MONGO_MOUNT_VOLUME}:/data/db
        environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        networks:
        - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmariadb:
        driver: local
    sailredis:
        driver: local
    sailmongodb:
        driver: local
    sailmeilisearch:
        driver: local
